1. Напишите программу `NumPy`, чтобы получить версию `NumPy` и показать конфигурацию сборки `NumPy`.

In [4]:
import numpy as np
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2270588361616
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


2. Напишите программу `NumPy`, чтобы получить справку по функции `add`.

In [87]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Напишите программу `NumPy`, чтобы проверить, не равен ли ни один из элементов заданного массива нулю.

In [21]:
not np.any(np.isclose(np.array([1]), 0))

True

4. Напишите программу `NumPy` для проверки того, является ли какой-либо из элементов заданного массива ненулевым.

In [26]:
not np.all(np.isclose(np.array([0]), 0))

False

    5. Напишите программу `NumPy` для поэлементной проверки заданного массива на конечность (не бесконечность или не число).

In [27]:
np.isfinite(np.array([0]))

array([ True])

6. Напишите программу `NumPy` для поэлементной проверки положительной или отрицательной бесконечности.

In [ ]:
np.isnan(np.array([0]))

7. Напишите программу `NumPy` для поэлементной проверкизаданного массива на значение NaN.

In [30]:
t = np.array([1, 2, 3+4j])
print(np.iscomplex(t))
print(np.isreal(t))
# what is the scalar type

[False False  True]
[ True  True False]


8. Напишите программу `NumPy` для поэлементной проверки комплексного числа, действительного числа данного массива. Также проверьте, является ли данное число скалярным типом или нет.

In [34]:
np.allclose(np.array([1, 2, 3]), np.array([1 + 1e-2, 2 + 1e-16, 3]))

False

9. Напишите программу `NumPy`, чтобы проверить, равны ли два массива по элементам в пределах допуска.

In [35]:
print(np.array([1, 2, 3]) > np.array([1, 2, 3]))
print(np.array([1, 2, 3]) >= np.array([1, 2, 3]))
print(np.array([1, 2, 3]) < np.array([1, 2, 3]))
print(np.array([1, 2, 3]) <= np.array([1, 2, 3]))

array([False, False, False])

10. Напишите программу `NumPy` для создания поэлементного сравнения (больше, больше_равно, меньше и меньше_равно) двух заданных массивов.

In [38]:
np.array_equal(np.array([1 + 1e-2, 2, 3]),  np.array([1, 2, 3]))

False

11. Напишите программу `NumPy` для создания поэлементного сравнения (равно, равно в пределах допуска) двух заданных массивов.

In [39]:
np.array([1, 7, 13, 105]).nbytes

16

12. Напишите программу `NumPy` для создания массива со значениями 1, 7, 13, 105 и определения размера памяти, занимаемой массивом.

In [45]:
np.concatenate((np.zeros(10), np.ones(10), 5 * np.ones(10)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

13. Напишите программу `NumPy` для создания массива из `10` нулей, `10` единиц и `10` пятерок.

In [47]:
np.arange(30, 70 + 1)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

14. Напишите программу `NumPy` для создания массива целых чисел от `30` до `70`.

In [48]:
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

15. Напишите программу `NumPy` для создания массива всех четных целых чисел от `30` до `70`.

In [49]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

16. Напишите программу `NumPy` для создания идентификационной матрицы `3x3`.

In [53]:
np.random.rand()

0.9820963033011999

17. Напишите программу `NumPy` для генерации случайного числа от `0` до `1`.

In [55]:
np.random.normal(size=15)

array([ 1.31227344,  0.42373349,  0.81280526,  0.44153497, -0.76740565,
        0.03368   , -0.20487264, -0.97090774, -1.4868597 ,  0.87483603,
       -1.62873073,  1.21789913,  1.93491239, -2.25412606, -1.78367656])

18. Напишите программу `NumPy` для создания массива из `15` случайных чисел из стандартного нормального распределения.

In [57]:
np.arange(15, 56)[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

19. Напишите программу `NumPy` для создания вектора со значениями в диапазоне от `15` до `55` и печати всех значений, кроме первого и последнего.

In [78]:
np.resize(np.arange(0, 13), (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

20. Напишите программу `NumPy` для создания массива `3X4` с использованием и итерацией по нему.

In [65]:
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

21. Напишите программу `NumPy` для создания вектора длины `10` со значениями, равномерно распределенными между `5` и `50`.

In [71]:
t = np.arange(0, 20)
t[np.logical_and(t >= 9, t <= 15)] *= -1
print(t)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


22. Напишите программу `NumPy` для создания вектора со значениями от `0` до `20` и изменения знака чисел в диапазоне от `9` до `15`.

In [72]:
np.random.randint(0, 11, size=5)

array([9, 9, 4, 5, 2])

23. Напишите программу `NumPy` для создания вектора длины `5`, заполненного произвольными целыми числами от `0` до `10`.

In [73]:
np.array([1, 2, 3]) * np.array([1, 2, 3])

array([1, 4, 9])

24. Напишите программу `NumPy` для умножения значений двух заданных векторов.

In [76]:
np.resize(np.arange(10, 22), (3, 4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

25. Напишите программу `NumPy` для создания матрицы `3x4`, заполненной значениями от `10` до `21`.

In [77]:
np.array([[1, 2, 3], [4, 5, 6]]).shape

(2, 3)

26. Напишите программу `NumPy` для определения количества строк и столбцов заданной матрицы.

In [79]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

27. Напишите программу `NumPy` для создания единичной матрицы `3x3`, т.е. диагональные элементы равны `1`, остальные равны `0`.

In [84]:
full_matrix = np.full((10, 10), 0)

# Шаг 2: Создание маски для элементов на границах
border_mask = np.ones((10, 10), dtype=bool)

# Удаление внутренних элементов из маски
border_mask[1:-1, 1:-1] = False
full_matrix[border_mask] = 1
print(full_matrix)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


28. Напишите программу `NumPy` для создания матрицы `10х10`, в которой элементы на границах будут равны `1`, а внутри `0`.

In [86]:
np.diag(np.arange(1, 6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

29. Напишите программу `NumPy` для создания нулевой матрицы `5x5` с элементами на главной диагонали, равными `1, 2, 3, 4, 5`.

30. Напишите программу `NumPy` для создания матрицы `4x4`, в которой `0` и `1` расположены в шахматном порядке, с нулями на главной диагонали.

31. Напишите программу `NumPy` для создания массива `3x3x3`, заполненного произвольными значениями.

32. Напишите программу `NumPy` для вычисления суммы всех элементов, суммы каждого столбца и суммы каждой строки заданного массива.

33. Напишите программу `NumPy` для вычисления скалярного произведения двух заданных векторов.

34. Напишите программу `NumPy` для добавления вектора в каждую строку заданной матрицы.

35. Напишите программу `NumPy` для сохранения данного массива в двоичный файл.

36. Напишите программу `NumPy` для сохранения двух заданных массивов в один файл в сжатом формате (формат `.npz`) и загрузите его.

37. Напишите программу `NumPy` для сохранения данного массива в текстовый файл и его загрузки.

38. Напишите программу `NumPy` для преобразования заданного массива в байты и загрузки его как массива.

39. Напишите программу `NumPy` для преобразования данного списка в массив, а затем снова преобразуйте его в список. Проверьте, равны ли исходный список и окончательный список.

40. Напишите программу `NumPy` для вычисления координат `x` и `y` точек на синусоиде и построения точек с помощью `matplotlib`.

41. Напишите программу `NumPy` для преобразования dtypes `NumPy` в собственные типы python.

42. Напишите программу `NumPy` для суммирования элементов матрицы. Если элемент в матрице равен `0`, мы не будем добавлять элемент ниже этого элемента.

In [ ]:
matrix = np.array([[1,2,0,4],[5,6,7,8],[1,0,3,4],[5,0,7,8]])
print(matrix)
mask = matrix != 0
print(mask)
mask = np.pad(mask, ((1,0),(0,0)), constant_values=True)[:-1]
print(mask)

print((mask*matrix).sum())


[[1 2 0 4]
 [5 6 7 8]
 [1 0 3 4]
 [5 0 7 8]]
[[ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]
 [ True False  True  True]]
[[ True  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]]
54


In [ ]:
np.pad(mask, ((1,0),(0,0)), constant_values=True)[:-1]

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

43. Напишите программу `NumPy` для поиска недостающих (`NaN`) данных в заданном массиве.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, np.nan, 4, 5, np.nan, 6, 7])


(array([3, 6]),)

44. Напишите программу `NumPy`, чтобы проверить, равны ли два массива (поэлементно) или нет.

45. Напишите программу `NumPy` для создания одномерного массива одно-, двух- и трехзначных чисел.

In [ ]:
import numpy as np
arr1 =np.arange(40)


46. Напишите программу `NumPy` для создания двумерного массива указанного формата.

47. Напишите программу `NumPy` для создания одномерного массива из сорока псевдослучайно сгенерированных значений. Выберите случайные числа из равномерного распределения между 0 и 1.

48. Напишите программу `NumPy` для создания двумерного массива случайных чисел формы `(8,5)`. Выберите случайные числа из нормального распределения `(200,7)`.

49. Напишите программу `NumPy` для генерации униформы, nоднородная случайная выборка из заданного одномерного массива с замещением и без замещения.

50. Напишите программу `NumPy` для создания массива `4x4` со случайными значениями, теперь создайте новый массив из указанного массива, поменяв местами первую и последнюю строки.

51. Напишите программу `NumPy` для создания нового массива заданной формы `(5,6)` и типа, заполненного нулями.

52. Напишите программу `NumPy` для сортировки заданного массива по строкам и столбцам в порядке возрастания.

53. Напишите программу `NumPy` для извлечения из заданного массива всех чисел, которые меньше и больше указанного числа.

54. Напишите программу `NumPy` для замены всех чисел в заданном массиве, которые равны, меньше и больше заданному числу.

55. Напишите программу `NumPy` для создания массива одинаковой формы и типа данных заданного массива.

56. Напишите программу `NumPy` для создания трехмерного массива формы `(3,5,4)` и установки переменной.

57. Напишите программу `NumPy` для создания массива `4x4`, теперь создайте новый массив из указанного массива, поменяв местами первый и последний, второй и третий столбцы.

58. Напишите программу `NumPy` для замены строк и столбцов заданного массива в обратном порядке.

In [89]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(np.flip(arr, axis=0))
print(np.flip(arr, axis=1))

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


59. Напишите программу `NumPy` для поэлементного умножения двух заданных массивов одинакового размера.

In [88]:
np.array([1, 2, 3]) * np.array([1, 2, 3])

array([1, 4, 9])