In [ ]:
import numpy as np
import matplotlib.pyplot as plt

1. Напишите программу `NumPy`, чтобы получить версию `NumPy` и показать конфигурацию сборки `NumPy`.

In [ ]:
print(np.__version__)
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

2. Напишите программу `NumPy`, чтобы получить справку по функции `add`.

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Напишите программу `NumPy`, чтобы проверить, не равен ли ни один из элементов заданного массива нулю.

In [ ]:
x = np.array([0, 1, 2, 3, 4])
np.all(x)

False

4. Напишите программу `NumPy` для проверки того, является ли какой-либо из элементов заданного массива ненулевым.

In [ ]:
x = np.array([0, 1, 2, 3, 4])
np.any(x)

5. Напишите программу `NumPy` для поэлементной проверки заданного массива на конечность (не бесконечность или не число).

In [ ]:
x = np.array([1, 0, np.nan, np.inf])
np.isfinite(x)

6. Напишите программу `NumPy` для поэлементной проверки положительной или отрицательной бесконечности.

In [ ]:
x = np.array([1, 0, np.nan, np.inf])
np.isinf(x)

7. Напишите программу `NumPy` для поэлементной проверкизаданного массива на значение NaN.

In [ ]:
x = np.array([1, 0, np.nan, np.inf])
np.isnan(x)

8. Напишите программу `NumPy` для поэлементной проверки комплексного числа, действительного числа данного массива. Также проверьте, является ли данное число скалярным типом или нет.

In [ ]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.iscomplex(x))
print(np.isreal(x))
print(np.isscalar(23.1))
print(np.isscalar([4.1]))

9. Напишите программу `NumPy`, чтобы проверить, равны ли два массива по элементам в пределах допуска.

In [ ]:
x = np.array([1.2, 1.123, 2.1324, 3, 2])
y = np.array([1.2, 1.124, 2.1325, 3, 2])
np.allclose(x,y, rtol=0.001)

True

10. Напишите программу `NumPy` для создания поэлементного сравнения (больше, больше_равно, меньше и меньше_равно) двух заданных массивов.

In [ ]:
x = np.array([1.2, 1.123, 2.1324, 3, 2])
y = np.array([1.2, 1.124, 2.1325, 3, 2])
print(np.greater(x, y))
print(np.greater_equal(x, y))
print(np.less(x, y))
print(np.less_equal(x, y))

11. Напишите программу `NumPy` для создания поэлементного сравнения (равно, равно в пределах допуска) двух заданных массивов.

In [ ]:
x = np.array([1.2, 1.123, 2.1324, 3, 2])
y = np.array([1.2, 1.124, 2.1325, 3, 2])
print(np.allclose(x,y, rtol=0.01))
print(np.array_equal(x,y))

True
False


12. Напишите программу `NumPy` для создания массива со значениями 1, 7, 13, 105 и определения размера памяти, занимаемой массивом.

In [ ]:
x = np.array([1, 7, 13, 105])
x.size * x.itemsize

13. Напишите программу `NumPy` для создания массива из `10` нулей, `10` единиц и `10` пятерок.

In [ ]:
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)

14. Напишите программу `NumPy` для создания массива целых чисел от `30` до `70`.

In [ ]:
print(np.arange(30,71))

15. Напишите программу `NumPy` для создания массива всех четных целых чисел от `30` до `70`.

In [ ]:
print(np.arange(30,71,2))

16. Напишите программу `NumPy` для создания идентификационной матрицы `3x3`.

In [ ]:
print(np.identity(3))

17. Напишите программу `NumPy` для генерации случайного числа от `0` до `1`.

In [ ]:
print(np.random.normal(0,1))

0.5856814303223871


18. Напишите программу `NumPy` для создания массива из `15` случайных чисел из стандартного нормального распределения.

In [ ]:
np.random.normal(0,1,15)

19. Напишите программу `NumPy` для создания вектора со значениями в диапазоне от `15` до `55` и печати всех значений, кроме первого и последнего.

In [ ]:
x = np.arrange(15,56)
print(x[1:-1])

20. Напишите программу `NumPy` для создания массива `3X4` с использованием и итерацией по нему.

In [ ]:
x = np.arange(10,22).reshape((3, 4))
for e in np.nditer(x):
  print(e,end=" ")

21. Напишите программу `NumPy` для создания вектора длины `10` со значениями, равномерно распределенными между `5` и `50`.

In [ ]:
np.linspace(10, 49, 5)

22. Напишите программу `NumPy` для создания вектора со значениями от `0` до `20` и изменения знака чисел в диапазоне от `9` до `15`.

In [ ]:
x = np.arange(20)
x[(x >= 9) & (x <= 15)] *= -1

23. Напишите программу `NumPy` для создания вектора длины `5`, заполненного произвольными целыми числами от `0` до `10`.

In [ ]:
np.random.randint(0, 11, 5)

24. Напишите программу `NumPy` для умножения значений двух заданных векторов.

In [ ]:
x = np.array([1, 2, 3, 5])
y = np.array([3, 4, 2, 5])
print(x*y)

25. Напишите программу `NumPy` для создания матрицы `3x4`, заполненной значениями от `10` до `21`.

In [ ]:
np.arange(10,22).reshape((3, 4))

26. Напишите программу `NumPy` для определения количества строк и столбцов заданной матрицы.

In [ ]:
x = np.arange(10,22).reshape((3, 4))
x.shape

27. Напишите программу `NumPy` для создания единичной матрицы `3x3`, т.е. диагональные элементы равны `1`, остальные равны `0`.

In [ ]:
np.eye(3)

28. Напишите программу `NumPy` для создания матрицы `10х10`, в которой элементы на границах будут равны `1`, а внутри `0`.

In [ ]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0

29. Напишите программу `NumPy` для создания нулевой матрицы `5x5` с элементами на главной диагонали, равными `1, 2, 3, 4, 5`.

In [ ]:
np.diag([1, 2, 3, 4, 5])

30. Напишите программу `NumPy` для создания матрицы `4x4`, в которой `0` и `1` расположены в шахматном порядке, с нулями на главной диагонали.

In [ ]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


31. Напишите программу `NumPy` для создания массива `3x3x3`, заполненного произвольными значениями.

In [ ]:
np.random.random((3, 3, 3))

32. Напишите программу `NumPy` для вычисления суммы всех элементов, суммы каждого столбца и суммы каждой строки заданного массива.

In [ ]:
x = np.arange(10,22).reshape((3, 4))
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

33. Напишите программу `NumPy` для вычисления скалярного произведения двух заданных векторов.

In [ ]:
x = np.array([1, 2, 3, 5])
y = np.array([3, 4, 2, 5])
np.dot(x, y)

34. Напишите программу `NumPy` для добавления вектора в каждую строку заданной матрицы.

In [ ]:
x = np.arange(10,22).reshape((3, 4))
v = np.array([1, 2, 3, 4])
result = np.empty_like(x)
for i in range(3):
  result[i, :] = x[i, :] + v
result

array([[11, 13, 15, 17],
       [15, 17, 19, 21],
       [19, 21, 23, 25]])

35. Напишите программу `NumPy` для сохранения данного массива в двоичный файл.

In [ ]:
x = np.arange(20)
np.save('temp_arra.npy', x)
x2 = np.load('temp_arra.npy')
np.array_equal(x,x2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

36. Напишите программу `NumPy` для сохранения двух заданных массивов в один файл в сжатом формате (формат `.npz`) и загрузите его.

In [ ]:
x = np.arange(10)
y = np.arange(11, 20)

np.savez('temp_arra.npz', x=x, y=y)

with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(np.array_equal(x, x2))
    print(np.array_equal(y, y2))

37. Напишите программу `NumPy` для сохранения данного массива в текстовый файл и его загрузки.

In [ ]:
x = np.arange(10)
np.savetxt("temp_array.npz", x)
x2 = np.loadtxt("temp_array.npz")

38. Напишите программу `NumPy` для преобразования заданного массива в байты и загрузки его как массива.

In [ ]:
x = np.arange(10)
x_bytes = x.tostring()
x2 = np.fromstring(x, dtype=x.dtype)
np.array_equal(x,x2)

39. Напишите программу `NumPy` для преобразования данного списка в массив, а затем снова преобразуйте его в список. Проверьте, равны ли исходный список и окончательный список.

In [ ]:
x = [[1,2],[3,4]]
x_arr = np.array(x)
x2 = x_arr.tolist()
x==x2

40. Напишите программу `NumPy` для вычисления координат `x` и `y` точек на синусоиде и построения точек с помощью `matplotlib`.

In [ ]:
x = np.arange(0, 3 * np.pi, 0.2)
y = np.sin(x)
plt.plot(x, y)
plt.show()

41. Напишите программу `NumPy` для преобразования dtypes `NumPy` в собственные типы python.

In [ ]:
x = np.float32(1)
print(type(x))
pyval = x.item()
print(type(pyval))

42. Напишите программу `NumPy` для суммирования элементов матрицы. Если элемент в матрице равен `0`, мы не будем добавлять элемент ниже этого элемента.

In [ ]:
matrix = np.array([[1,2,0,4],[5,6,7,8],[1,0,3,4],[5,0,7,8]])
mask = matrix != 0
mask = np.pad(mask, ((1,0),(0,0)), constant_values=True)[:-1]

print((mask*matrix).sum())


[[1 2 0 4]
 [5 6 7 8]
 [1 0 3 4]
 [5 0 7 8]]
[[ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]
 [ True False  True  True]]
[[ True  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]]
54


43. Напишите программу `NumPy` для поиска недостающих (`NaN`) данных в заданном массиве.

In [ ]:
a = np.array([1, 2, 3, np.nan, 4, 5, np.nan, 6, 7])
np.isnan(a)

(array([3, 6]),)

44. Напишите программу `NumPy`, чтобы проверить, равны ли два массива (поэлементно) или нет.

In [ ]:
x = np.array([1, 2, 3, 5])
y = np.array([3, 4, 2, 5])
np.equal(x, y)

45. Напишите программу `NumPy` для создания одномерного массива одно-, двух- и трехзначных чисел.

In [ ]:
import numpy as np
arr =np.arange(10)
arr =np.arange(10,100)
arr =np.arange(100,200)


46. Напишите программу `NumPy` для создания двумерного массива указанного формата.

In [ ]:
np.arange(1, 151).reshape(15, 10)

47. Напишите программу `NumPy` для создания одномерного массива из сорока псевдослучайно сгенерированных значений. Выберите случайные числа из равномерного распределения между 0 и 1.

In [ ]:
np.random.rand(40)

array([0.2310448 , 0.30720638, 0.43940935, 0.41602892, 0.02503188,
       0.14287301, 0.46594525, 0.31688238, 0.22935571, 0.89641387,
       0.19452663, 0.05476066, 0.18293202, 0.33950741, 0.00272461,
       0.53228732, 0.60137963, 0.57534414, 0.36288396, 0.73248098,
       0.33030766, 0.93415988, 0.53933263, 0.84662925, 0.7367508 ,
       0.89682269, 0.74778607, 0.02864283, 0.24236985, 0.87337976,
       0.05045499, 0.47687247, 0.83074967, 0.37130414, 0.32231884,
       0.12793887, 0.30562967, 0.94244316, 0.20474839, 0.96456034])

48. Напишите программу `NumPy` для создания двумерного массива случайных чисел формы `(8,5)`. Выберите случайные числа из нормального распределения `(200,7)`.

In [ ]:
np.random.normal(200, 7, (8,5))

array([[193.76213722, 210.96395276, 188.69524303, 209.23264209,
        198.13874056],
       [203.91407673, 202.34569792, 207.80392984, 193.85681607,
        205.13314236],
       [194.75227463, 207.93711481, 199.57200242, 193.12195615,
        198.73644469],
       [200.52273356, 197.60508642, 208.28190909, 197.99646924,
        210.84314433],
       [207.89571496, 195.90452274, 200.19998157, 205.17437717,
        204.18607114],
       [205.94429801, 188.72454865, 202.53313761, 195.44785053,
        208.72511783],
       [198.78523785, 188.91248911, 204.82383238, 196.58993551,
        201.5560953 ],
       [203.01534321, 212.99569377, 196.6020905 , 204.950115  ,
        202.05946195]])

49. Напишите программу `NumPy` для генерации униформы, nоднородная случайная выборка из заданного одномерного массива с замещением и без замещения.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Generate a uniform random sample with replacement
print(np.random.choice(x, size=5, replace=True))

# Generate a uniform random sample without replacement
print(np.random.choice(x, size=5, replace=False))

50. Напишите программу `NumPy` для создания массива `4x4` со случайными значениями, теперь создайте новый массив из указанного массива, поменяв местами первую и последнюю строки.

In [ ]:
x = np.random.rand(16).reshape(4,4)
x[[0,-1],:] = x[[-1,0],:]

51. Напишите программу `NumPy` для создания нового массива заданной формы `(5,6)` и типа, заполненного нулями.

In [ ]:
x = np.zeros((5,6), dtype=np.float32)

52. Напишите программу `NumPy` для сортировки заданного массива по строкам и столбцам в порядке возрастания.

In [ ]:
x = np.arange(1, 151).reshape(15, 10)
print(np.sort(x))
print(np.sort(x, axis=0))

53. Напишите программу `NumPy` для извлечения из заданного массива всех чисел, которые меньше и больше указанного числа.

In [ ]:
x = np.arange(1, 151)
print(x[x>15])
print(x[x<15])

54. Напишите программу `NumPy` для замены всех чисел в заданном массиве, которые равны, меньше и больше заданному числу.

In [ ]:
x = np.arange(1, 151)
x[x>15] = 1
x[x<15] = 0
print(x)

55. Напишите программу `NumPy` для создания массива одинаковой формы и типа данных заданного массива.

In [ ]:
x = np.arange(1, 151)
np.zeros_like(x)

56. Напишите программу `NumPy` для создания трехмерного массива формы `(3,5,4)` и установки переменной.

In [ ]:
nums = np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],

              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],
               [0, 1, 9, 1]],

              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],
               [2, 0, 2, 8]]])

57. Напишите программу `NumPy` для создания массива `4x4`, теперь создайте новый массив из указанного массива, поменяв местами первый и последний, второй и третий столбцы.

In [ ]:
x = np.arrange(16).reshape(4,4)
new_x = x[:, ::-1]

58. Напишите программу `NumPy` для замены строк и столбцов заданного массива в обратном порядке.

In [ ]:
x = np.arrange(16).reshape(4,4)
x[::-1, ::-1]

59. Напишите программу `NumPy` для поэлементного умножения двух заданных массивов одинакового размера.

In [ ]:
x = np.arrange(16).reshape(4,4)
y = np.arrange(10,26).reshape(4,4)
np.multiply(x,y)